config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  resources :users
  resources :blogs
  resources :sessions
  resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
   belongs_to :user
   has_many :favorites, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  before_validation { email.downcase! }
  has_secure_password
  has_many :blogs
  has_many :favorites, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :login_required
  private
    def login_required
      redirect_to new_session_path unless current_user
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all.order(created_at: :desc)
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    @blog =Blog.find(params[:id])
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog = current_user.blogs.build(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.fetch(:blog, {}).permit(:title,:content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new,:create]

  def new
  end

  def create
    #Userテーブルから"session"パラメータの"email"を取得し検索してuserに代入する。
    #userには"name","email","password"が入る
    user = User.find_by(email: params[:session][:email].downcase)

    #1.authenticate = userに入っているパスワードとparams:passwordを比較する。
    #2.合っていたら userを返す，違っていたらfalseを返す
    #3.user && user => Rubyは文字列はtrue扱いなので ture && tureの式になる。
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :login_required, only: [:new,:create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @favorite = current_user.favorites


  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :title ,"タイトル" %>
  <%= form.text_field :title %>
  <%= form.label :content ,"内容" %>
  <%= form.text_field :content %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog(blogs/edit)</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs(blogs/index)</h1>
<table>
  <thead>
    <tr>
      <th colspan="3">タイトル</th>
      <th>名前</th>
      <th colspan="3">内容</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td colspan="3"><%=blog.title%></td>
        <td colspan="3"><%=blog.user.name%></td>
        <td colspan="3"><%=blog.content%></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog(blogs/new)</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Show(blogs/show)</h1>
<td colspan="3"><%=@blog.title%></td>
<td colspan="3"><%=@blog.user.name%></td>
<td colspan="3"><%=@blog.content%></td>

<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if logged_in? %>
      <h2>ログイン中</h2>
      <%= link_to "ブログ一覧", blogs_path %>
      <%= link_to "プロフィール", user_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <h2>未ログイン</h2>
      <%= link_to "新規登録", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
      <%= link_to "ブログ一覧（アクセス制限確認用）", blogs_path %>
    <% end %>
      <p>↑ layouts/application.html.erb ↑</p>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<h1>新規登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>
<p><%= f.label :email %></p>
<p><%= f.email_field :email %></p>
<p><%= f.label :password %></p>
<p><%= f.password_field :password %></p>
<p><%= f.submit "アカウントを作成する" %></p>
<% end %>
<%=link_to "ログイン画面", new_session_path %>

app/views/users/show.html.erb
<h1>プロフィール(users/show)</h1>
<p>名前: <%= @user.name %></p>
<p>メールアドレス: <%= @user.email %></p>


<% @favorite.each do |favorite| %>
  <tr>
    <td><%= favorite.blog.title %></td>
    <td><%= favorite.blog.content %></td>
    <td><%= link_to 'Show', blog_path(favorite.blog_id) %></td>
  </tr>
<% end %>